Fix for missing asciidoc3 module error.
Fix the follwong missing asciidoc3 module error.

Traceback (most recent call last):
  File "/root/asciidoc3.git/tests/asciidoc3api.py", line 188, in __import_asciidoc3
    importlib.import_module('asciidoc3')
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'asciidoc3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/testasciidoc3.py", line 433, in <module>
    tests.update(number, backend, force=force)
  File "tests/testasciidoc3.py", line 344, in update
    test.update(backend, force=force)
  File "tests/testasciidoc3.py", line 224, in update
    self.update_expected(backend)
  File "tests/testasciidoc3.py", line 203, in update_expected
    lines = self.generate_expected(backend)
  File "tests/testasciidoc3.py", line 191, in generate_expected
    asciidoc3 = asciidoc3api.AsciiDoc3API()
  File "/root/asciidoc3.git/tests/asciidoc3api.py", line 154, in __init__
    self.__import_asciidoc3()
  File "/root/asciidoc3.git/tests/asciidoc3api.py", line 191, in __import_asciidoc3
    raise AsciiDoc3Error('failed to import ' + self.cmd)
asciidoc3api.AsciiDoc3Error: failed to import /usr/bin/asciidoc3